client: # https://www.elastic.co/guide/en/elasticsearch/client/curator/5.6/configfile.html
  hosts:
    - localhost
  port: 9200
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  http_auth:
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile: /home/ec2-user/ES-Tutorial-7/tools/curator/logs/curator.log
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
